//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.02 at 02:06:10 PM CST 
//


package com.cwms.qm.model.bo;

import javax.xml.bind.annotation.*;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}batchCode"/>
 *         &lt;element ref="{}productDate"/>
 *         &lt;element ref="{}expireDate"/>
 *         &lt;element ref="{}produceCode"/>
 *         &lt;element ref="{}inventoryType"/>
 *         &lt;element ref="{}actualQty"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "batchCode",
    "productDate",
    "expireDate",
    "produceCode",
    "inventoryType",
    "actualQty",
        "weight"
})
@XmlRootElement(name = "batch")
public class Batch {

    @XmlElement(required = true)
    protected String batchCode;
    @XmlElement(required = true)
    protected String productDate;
    @XmlElement(required = true)
    protected String expireDate;
    @XmlElement(required = true)
    protected String produceCode;
    @XmlElement(required = true)
    protected String inventoryType;
    @XmlElement(required = true)
    protected String actualQty;
    @XmlElement(required = true)
    protected String weight;

    /**
     * Gets the value of the batchCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBatchCode() {
        return batchCode;
    }

    /**
     * Sets the value of the batchCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBatchCode(String value) {
        this.batchCode = value;
    }

    /**
     * Gets the value of the productDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductDate() {
        return productDate;
    }

    /**
     * Sets the value of the productDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductDate(String value) {
        this.productDate = value;
    }

    /**
     * Gets the value of the expireDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpireDate() {
        return expireDate;
    }

    /**
     * Sets the value of the expireDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpireDate(String value) {
        this.expireDate = value;
    }

    /**
     * Gets the value of the produceCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProduceCode() {
        return produceCode;
    }

    /**
     * Sets the value of the produceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProduceCode(String value) {
        this.produceCode = value;
    }

    /**
     * Gets the value of the inventoryType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInventoryType() {
        return inventoryType;
    }

    /**
     * Sets the value of the inventoryType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInventoryType(String value) {
        this.inventoryType = value;
    }

    /**
     * Gets the value of the actualQty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActualQty() {
        return actualQty;
    }

    /**
     * Sets the value of the actualQty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActualQty(String value) {
        this.actualQty = value;
    }

    public String getWeight() {
        return weight;
    }

    public void setWeight(String weight) {
        this.weight = weight;
    }
}
