//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.02 at 07:57:57 PM CST 
//


package com.cwms.qm.model.bo;

import java.math.BigInteger;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}totalOrderLines"/>
 *         &lt;element ref="{}entryOrderCode"/>
 *         &lt;element ref="{}ownerCode"/>
 *         &lt;element ref="{}warehouseCode"/>
 *         &lt;element ref="{}entryOrderId"/>
 *         &lt;element ref="{}entryOrderType"/>
 *         &lt;element ref="{}outBizCode"/>
 *         &lt;element ref="{}confirmType"/>
 *         &lt;element ref="{}status"/>
 *         &lt;element ref="{}operateTime"/>
 *         &lt;element ref="{}remark"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "totalOrderLines",
    "entryOrderCode",
    "ownerCode",
    "warehouseCode",
    "entryOrderId",
    "entryOrderType",
    "outBizCode",
    "confirmType",
    "status",
    "operateTime",
    "remark"
})
@XmlRootElement(name = "entryOrder")
public class EntryOrder {

    @XmlElement(required = true)
    protected BigInteger totalOrderLines;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String entryOrderCode;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String ownerCode;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String warehouseCode;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String entryOrderId;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String entryOrderType;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String outBizCode;
    @XmlElement(required = true)
    protected int confirmType;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String status;
    @XmlElement(required = true)
    protected String operateTime;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String remark;

    /**
     * Gets the value of the totalOrderLines property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalOrderLines() {
        return totalOrderLines;
    }

    /**
     * Sets the value of the totalOrderLines property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalOrderLines(BigInteger value) {
        this.totalOrderLines = value;
    }

    /**
     * Gets the value of the entryOrderCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntryOrderCode() {
        return entryOrderCode;
    }

    /**
     * Sets the value of the entryOrderCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntryOrderCode(String value) {
        this.entryOrderCode = value;
    }

    /**
     * Gets the value of the ownerCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwnerCode() {
        return ownerCode;
    }

    /**
     * Sets the value of the ownerCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwnerCode(String value) {
        this.ownerCode = value;
    }

    /**
     * Gets the value of the warehouseCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWarehouseCode() {
        return warehouseCode;
    }

    /**
     * Sets the value of the warehouseCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWarehouseCode(String value) {
        this.warehouseCode = value;
    }

    /**
     * Gets the value of the entryOrderId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntryOrderId() {
        return entryOrderId;
    }

    /**
     * Sets the value of the entryOrderId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntryOrderId(String value) {
        this.entryOrderId = value;
    }

    /**
     * Gets the value of the entryOrderType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntryOrderType() {
        return entryOrderType;
    }

    /**
     * Sets the value of the entryOrderType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntryOrderType(String value) {
        this.entryOrderType = value;
    }

    /**
     * Gets the value of the outBizCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutBizCode() {
        return outBizCode;
    }

    /**
     * Sets the value of the outBizCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutBizCode(String value) {
        this.outBizCode = value;
    }

    /**
     * Gets the value of the confirmType property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public int getConfirmType() {
        return confirmType;
    }

    /**
     * Sets the value of the confirmType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setConfirmType(int value) {
        this.confirmType = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the operateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperateTime() {
        return operateTime;
    }

    /**
     * Sets the value of the operateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperateTime(String value) {
        this.operateTime = value;
    }

    /**
     * Gets the value of the remark property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemark() {
        return remark;
    }

    /**
     * Sets the value of the remark property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemark(String value) {
        this.remark = value;
    }

}
