//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.02 at 02:06:10 PM CST 
//


package com.cwms.qm.model.bo;

import javax.xml.bind.annotation.*;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}orderLineNo"/>
 *         &lt;element ref="{}sourceOrderCode"/>
 *         &lt;element ref="{}subSourceOrderCode"/>
 *         &lt;element ref="{}itemCode"/>
 *         &lt;element ref="{}itemId"/>
 *         &lt;element ref="{}inventoryType"/>
 *         &lt;element ref="{}planQty"/>
 *         &lt;element ref="{}actualQty"/>
 *         &lt;element ref="{}batchCode"/>
 *         &lt;element ref="{}productDate"/>
 *         &lt;element ref="{}expireDate"/>
 *         &lt;element ref="{}produceCode"/>
 *         &lt;element ref="{}batchs"/>
 *         &lt;element ref="{}qrCode"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "orderLineNo",
    "sourceOrderCode",
    "subSourceOrderCode",
    "itemCode",
    "itemId",
    "inventoryType",
    "planQty",
    "actualQty",
    "batchCode",
    "productDate",
    "expireDate",
    "produceCode",
    "batchs",
    "qrCode",
    "ownerCode",
    "itemName",
    "outBizCode",
    "remark",
        "weight"
})
@XmlRootElement(name = "orderLine")
public class OrderLine {

    @XmlElement(required = true)
    protected String orderLineNo;
    @XmlElement(required = true)
    protected String sourceOrderCode;
    @XmlElement(required = true)
    protected String subSourceOrderCode;
    @XmlElement(required = true)
    protected String itemCode;
    @XmlElement(required = true)
    protected String itemId;
    @XmlElement(required = true)
    protected String inventoryType;
    @XmlElement(required = true)
    protected int planQty;
    @XmlElement(required = true)
    protected int actualQty;
    @XmlElement(required = true)
    protected String batchCode;
    @XmlElement(required = true)
    protected String productDate;
    @XmlElement(required = true)
    protected String expireDate;
    @XmlElement(required = true)
    protected String produceCode;
    @XmlElement(required = true)
    protected Batchs batchs;
    @XmlElement(required = true)
    protected String qrCode;

    @XmlElement(required = true)
    protected String ownerCode;

    @XmlElement(required = true)
    protected String itemName;

    @XmlElement(required = true)
    private String outBizCode;

    @XmlElement(required = true)
    private String remark;

    @XmlElement(required = true)
    private Double weight;

    public String getOutBizCode()
    {
        return outBizCode;
    }

    public void setOutBizCode(String outBizCode)
    {
        this.outBizCode = outBizCode;
    }

    public String getRemark()
    {
        return remark;
    }

    public void setRemark(String remark)
    {
        this.remark = remark;
    }

    public String getOwnerCode()
    {
        return ownerCode;
    }

    public void setOwnerCode(String ownerCode)
    {
        this.ownerCode = ownerCode;
    }

    public String getItemName()
    {
        return itemName;
    }

    public void setItemName(String itemName)
    {
        this.itemName = itemName;
    }

    /**
     * Gets the value of the orderLineNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderLineNo() {
        return orderLineNo;
    }

    /**
     * Sets the value of the orderLineNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderLineNo(String value) {
        this.orderLineNo = value;
    }

    /**
     * Gets the value of the sourceOrderCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceOrderCode() {
        return sourceOrderCode;
    }

    /**
     * Sets the value of the sourceOrderCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceOrderCode(String value) {
        this.sourceOrderCode = value;
    }

    /**
     * Gets the value of the subSourceOrderCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubSourceOrderCode() {
        return subSourceOrderCode;
    }

    /**
     * Sets the value of the subSourceOrderCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubSourceOrderCode(String value) {
        this.subSourceOrderCode = value;
    }

    /**
     * Gets the value of the itemCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemCode() {
        return itemCode;
    }

    /**
     * Sets the value of the itemCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemCode(String value) {
        this.itemCode = value;
    }

    /**
     * Gets the value of the itemId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemId() {
        return itemId;
    }

    /**
     * Sets the value of the itemId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemId(String value) {
        this.itemId = value;
    }

    /**
     * Gets the value of the inventoryType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInventoryType() {
        return inventoryType;
    }

    /**
     * Sets the value of the inventoryType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInventoryType(String value) {
        this.inventoryType = value;
    }

    public int getPlanQty()
    {
        return planQty;
    }

    public void setPlanQty(int planQty)
    {
        this.planQty = planQty;
    }

    public int getActualQty()
    {
        return actualQty;
    }

    public void setActualQty(int actualQty)
    {
        this.actualQty = actualQty;
    }

    /**
     * Gets the value of the batchCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBatchCode() {
        return batchCode;
    }

    /**
     * Sets the value of the batchCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBatchCode(String value) {
        this.batchCode = value;
    }

    /**
     * Gets the value of the productDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductDate() {
        return productDate;
    }

    /**
     * Sets the value of the productDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductDate(String value) {
        this.productDate = value;
    }

    /**
     * Gets the value of the expireDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpireDate() {
        return expireDate;
    }

    /**
     * Sets the value of the expireDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpireDate(String value) {
        this.expireDate = value;
    }

    /**
     * Gets the value of the produceCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProduceCode() {
        return produceCode;
    }

    /**
     * Sets the value of the produceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProduceCode(String value) {
        this.produceCode = value;
    }

    /**
     * Gets the value of the batchs property.
     * 
     * @return
     *     possible object is
     *     {@link Batchs }
     *     
     */
    public Batchs getBatchs() {
        return batchs;
    }

    /**
     * Sets the value of the batchs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Batchs }
     *     
     */
    public void setBatchs(Batchs value) {
        this.batchs = value;
    }

    /**
     * Gets the value of the qrCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQrCode() {
        return qrCode;
    }

    /**
     * Sets the value of the qrCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQrCode(String value) {
        this.qrCode = value;
    }

    public Double getWeight() {
        return weight;
    }

    public void setWeight(Double weight) {
        this.weight = weight;
    }
}
