//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.22 at 06:28:51 ���� CST 
//

package com.cwms.qm.model;

import javax.xml.bind.annotation.*;

import com.cwms.qm.model.bo.EntryOrder;
import com.cwms.qm.model.bo.OrderLines;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "entryOrder",
    "orderLines"
})
@XmlRootElement(name = "request")
public class QmInboundFeekBackDto
{
    @XmlElement(required = true)
    protected EntryOrder entryOrder;

    @XmlElement(required = true)
    protected OrderLines orderLines;

    /**
     * Gets the value of the entryOrder property.
     *
     * @return possible object is
     * {@link EntryOrder }
     */
    public EntryOrder getEntryOrder()
    {
        return entryOrder;
    }

    /**
     * Sets the value of the entryOrder property.
     *
     * @param value allowed object is
     *              {@link EntryOrder }
     */
    public void setEntryOrder(EntryOrder value)
    {
        this.entryOrder = value;
    }

    /**
     * Gets the value of the orderLines property.
     *
     * @return possible object is
     * {@link OrderLines }
     */
    public OrderLines getOrderLines()
    {
        return orderLines;
    }

    /**
     * Sets the value of the orderLines property.
     *
     * @param value allowed object is
     *              {@link OrderLines }
     */
    public void setOrderLines(OrderLines value)
    {
        this.orderLines = value;
    }

}
